on: [push, workflow_dispatch]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-1'

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Synth CDK
        run: cdk synth

      - name: CDK Deploy
        run: |
          cdk deploy --app ./build/cdk.out --require-approval never "*"

